export const actionNames = {
    ADD_RACE: 'ADD-RACE',
    NEW_EMPTY_RACE: 'NEW-EMPTY-RACE',
    UPDATE_RACE: 'UPDATE-RACE',
    ON_CHANGE_NEW_RACE: 'ON-CHANGE-NEW-RACE',
    ON_CHANGE_PRE_CREATED_RACE_NAME: 'ON-CHANGE-PRE-CREATED-RACE-NAME',
}

