export const actionNames = {
    ADD_RACE: 'ADD-RACE',
    NEW_EMPTY_RACE: 'NEW-EMPTY-RACE',
    UPDATE_RACE: 'UPDATE-RACE',
    ON_CHANGE_NEW_RACE: 'ON-CHANGE-NEW-RACE',
    ON_CHANGE_PRE_CREATED_RACE_NAME: 'ON-CHANGE-PRE-CREATED-RACE-NAME',
    GAME_NEXT_STEP: 'GAME-NEXT-STEP',
    ADD_PLAYER:'ADD-PLAYER',
    REMOVE_PLAYER:'REMOVE-PLAYER',
    LOAD_RACES: 'LOAD-RACES',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    GET_ALL_RACES: 'GET_ALL_RACES'
}

